#!/bin/bash
mvn package
cp target/dynamic-map-0.1.0.jar /opt/spark/jars
/opt/spark/bin/spark-submit --class map.Application --master spark://master:7077 --executor-memory 4G target/dynamic-map-0.1.0.jar
